### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by vaishnavitripa** [MicrosoftDocs/data-tools#7]
I have an issue related to "spawn Unknown system error -86" this error that is not supporting the extension to activate. Firstly, it is not downloading directly. so I have to download it manually from other source. Secondly, it is showing error and not activating when I am clicking on import wizard. please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62842956-ffb7-730a-7043-3a03207bea85
* Version Independent ID: 62842956-ffb7-730a-7043-3a03207bea85
* Content: [SQL Server Import Extension - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/extensions/sql-server-import-extension?view=sql-server-ver16)
* Content Source: [azure-data-studio/extensions/sql-server-import-extension.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/extensions/sql-server-import-extension.md)
* Service: **azure-data-studio**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
Hi @vaishnavitripa - this sounds like an issue with ADS, not a docs issue.  Can you please log an issue in GitHub so that it can be reviewed by someone in engineering?  Here is the link to the repo: https://github.com/microsoft/azuredatastudio/issues 

However, you can also log an issue from within ADS by going to Help > Report Issue.  Thanks.

**Comment by erinstellato-ms** [comment]
#please-close

**Comment by rwestMSFT** [comment]
There does not appear to be actionable feedback here. Closing the issue.
